### PR TITLE
Add a servant/beam snapshot

### PR DESCRIPTION
**Pull request by quasi-coherent**

### CODE REVIEW

**Comment by fiadliel** [comment]
Should we update to LTS 13.14 or 13.15?

**Comment by andreyk0** [comment]
Yeah, lts bump would make sense if there are no crazy issues with that.

**Comment by fiadliel** [comment]
So it should be a new resolver `er-lts-13.15.0.yaml` then? Is there a policy around when it's okay to change an existing resolver, versus creating a new one? (stack seems to assume that remote resolvers are immutable).

**Comment by quasi-coherent** [comment]
Yeah, I don't think it's OK to change a remote snapshot.  Anyway, I'd like to keep this built off of lts-13.9.0 because that's what I've tested everything with.

**Comment by fiadliel** [comment]
Ah, maybe we make a `er-lts-13.9.1.yaml` with this change, and then `er-lts-13.15.0.yaml` without it?

**Comment by andreyk0** [comment]
Pretty sure it's *not* Ok to change existing snapshot :)
@fiadliel : your suggestion sounds good. What do we do about amazonka though? You ran into issues with the way I set up previous er lts snapshot (long stack start times).

**Comment by quasi-coherent** [comment]
Updated the name per the suggestion of @fiadliel 

Mind if I get an approval?

**Comment by fiadliel** [comment]
@andreyk0 That can be an issue for another PR. Would be great to figure out if there's a way to solve it though.

**Review by andreyk0 — APPROVED** [review]
🍣 🍶

**Comment by quasi-coherent** [comment]
> 🍣 🍶

Much obliged, sir.

**Pull request merged**
